server:
  port: 8090
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
 #  数据源其他配置
#    initialSize : 5
#    minIdle: 5
#    maxActive: 20

#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validaionQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
    #    配置监控统计拦截的filters 去掉后监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500
  jackson:
    local-date-time-format: yyyy-MM-dd HH:mm:ss
    local-date-format: yyyy-MM-dd
    local-time-format: HH:mm:ss
    generator:
      write-numbers-as-strings: true
logging:
  level:
    root: info
    com.money.fimsystem.business.mapper: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  mapper-locations:
    - mapper/business/*
  type-aliases-package: com.money.fimsystem.common.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: id_worker


