spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://43.139.36.238:3306/fimdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:META-INF/mybatis/*Mapper.xml,classpath:META-INF/mybatis/*-mapper.xml,classpath:META-INF/tbmanager/*Mapper.xml

minio:
  url: http://172.27.96.200:9001
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: fim