spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://43.139.36.238:3306/fimdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  redis:
    host: 43.139.36.238
    port: 6379
    password: 123456
    lettuce:
      pool:
        #        连接池最大连接数
        max-active: 8
        #最大阻塞等待时间
        max-wait: -1
        #最大空闲连接
        max-idle: 8
        #连接超时时间（ms）
    connect-timeout: 5000ms


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:META-INF/mybatis/*Mapper.xml,classpath:META-INF/mybatis/*-mapper.xml,classpath:META-INF/tbmanager/*Mapper.xml

minio:
  url: http://192.168.31.133:30202
  accessKey: admin
  secretKey: admin123456
  bucketName: fim

